### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by santi-rodriguez** [LEB-EPFL/MitoSplit-Net#1]
It would be nice that the name of the project includes:
1. Mito
2. Split / Division
3. Deep / DL / Net 

Some options are:
- MitoSplitNet
- MitoDivNet
- DeepMitoSplit

Simpler alternatives:
- Mito_DL
- MitoNet
- MitoSplit
(DeepSplit and DeepMito already exist)

Any preference or good ideas?

**Comment by wl-stepp** [comment]
I think MitoSplit-Net is a good option for now, I vote close.
