### ISSUE TITLE
Ground truth processing

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/MitoSplit-Net#2]
Martin Weigert commented that the ground truth maybe should be 'binary'. My solution to this was to choose a threshold and delete every event that is below that threshold. Every event that is above the threshold becomes a disk at the moment. The function for this in the moment is in Mito2Drp1.py -> prepareProc.
After further discussion with Martin. A first good step would be to replace the disk with a gaussian with maximum 255, this should be easier for the network to replicate.

**Comment by santi-rodriguez** [comment]
Ok, that's interesting. I will implement it and evaluate the differences.

**Comment by wl-stepp** [comment]
Nice approach in the preprocessing norebook, looks promising. I didn't know about segmentation.clear_border, already learned something :)

**Comment by wl-stepp** [comment]
I can't answer to cards in the project tab. So I will answer here.
What is in Proc.h5 is a output of some image analysis that Dora has done by a Hessian approach. I will attach the presentation where Dora discussed this a little bit. I don't think we have the code for this, but I can ask Dora if she has that if you would like to have a look. Might be in Matlab though.
Dora later went in an curated this calculated dataset by hand by adding obvious events that where not caught by the calculation or deleting wrong events out.
Yes, we use that as 'ground truth' for the training.

Full credit to Dora Mahecic for these resources!
[20201022_MWmeeting (1).pptx](https://github.com/LEB-EPFL/MitoSplit-Net/files/6783036/20201022_MWmeeting.1.pptx)

[github.pptx](https://github.com/LEB-EPFL/MitoSplit-Net/files/6783029/github.pptx)

**Comment by santi-rodriguez** [comment]
Ok, this cleared my doubts. 

It would be useful to get access to that code if we were interested in exploring other approaches at that level. Right now, I will keep on working with this ground truth, because I think it is accurate enough.

Thanks Willi!

**Comment by santi-rodriguez** [comment]
The full GT preprocessing pipeline is explained and implemented in preprocessing.ipynb, section "GT", subsection "Filter events by mean probability of division and replace each fission by a gaussian disk".

For the source code, you can take a look at preprocessing.py, lines 79-104 corresponding to the [prepareProc](https://github.com/LEB-EPFL/MitoSplit-Net/blob/307ddcdd8c4f13f8091f07a69c6082ee593b08e6/mitosplit-net/preprocessing.py#L79) function.

**Comment by wl-stepp** [comment]
Awesome, very informative! Can we link that file and a very short 2 sentence summary in the README? So the readme is a starting point for someone coming into the project?

**Comment by santi-rodriguez** [comment]
It sounds good, I will write about it in the README. Thanks for the feedback!

**Comment by wl-stepp** [comment]
We could think about using weighted-centroid instead of just centroid for the center positions of the regions. I think this would place the position closer to the actual maximum of the peak.
