### ISSUE TITLE
Writing a Python module

### ISSUE THREAD

**Issue by santi-rodriguez** [LEB-EPFL/MitoSplit-Net#7]
Convert all the .ipynb to .py so other people can reuse the code.

**Comment by wl-stepp** [comment]
Yes, also have a folder structure to organize things into preprocessing, training etc. submodules. Each folder needs an _init_.py file etc. Maybe you can have a look into how to set that up, so it's not too much work later.

**Comment by santi-rodriguez** [comment]
You are right. I will certainly look into the required files for creating a module. Thanks!
