### ISSUE TITLE
Output dimensions

### ISSUE THREAD

**Issue by wl-stepp** [LEB-EPFL/MitoSplit-Net#8]
Concerning:
https://github.com/LEB-EPFL/MitoSplit-Net/projects/2#card-64393135

ATS code:
Why is an extra dimension added on top of the one for different channels?

output_data= output_data.reshape(output_data.shape[0], 128, 128, 1, 1)

**Comment by wl-stepp** [comment]
Can you specify a little closer where in the code that is?

**Comment by santi-rodriguez** [comment]
The line is in [this Jupyter notebook](https://github.com/LEB-EPFL/ATS/blob/master/SmartMicro/20201014_Mito2Drp1.ipynb), which I was using as a reference. To be more precise, it is in the "Import, process, and shape the dataset" section, where Proc.h5 is loaded. 

However, here you can see that [the analogous line in the .py version](https://github.com/LEB-EPFL/ATS/blob/993a87fb38e3c9b06cd13cc1c53fcb19c604eace/SmartMicro/Mito2Drp1.py#L112) is different. As I would expect, in this case, the output and [input dimensions](https://github.com/LEB-EPFL/ATS/blob/993a87fb38e3c9b06cd13cc1c53fcb19c604eace/SmartMicro/Mito2Drp1.py#L43) match with each other.

Please, correct me if I am wrong, but aren't these two files in disagreement?

**Comment by wl-stepp** [comment]
Ah ok, I was looking in the .py file. I think I took it out because we never actually use it. I think it was in there for some 'historic' reason.
For the models you should have a look at the .py file anyways, as the model that does not depend on the 128x128 input data for inference is only there.
Also note that model_version == '210219' is not actually deeper as the code is at the moment.

**Comment by santi-rodriguez** [comment]
Ok, then the .py file will be my reference. Thanks Willi!
